---
  - name: Install httpd package
    yum:
      name: httpd
      state: present

  - name: start service
    service:
      name: httpd
      state: started
      enabled: true

  - name: deliver html content
    copy:
      src: html/
      dest: "/var/www/vhosts/{{ ansible_hostname }}"

  - name: template vhost file
    template:
      src: vhost.conf.j2
      dest: /etc/httpd/conf.d/vhost.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart httpd
